"""empty message

Revision ID: 0bde09d9d81e
Revises: b89697371bf7
Create Date: 2020-05-10 23:10:08.977079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bde09d9d81e'
down_revision = 'b89697371bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tag')
    # ### end Alembic commands ###
