"""empty message

Revision ID: 0cd4daa367db
Revises: 0bde09d9d81e
Create Date: 2020-05-10 23:11:38.342918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd4daa367db'
down_revision = '0bde09d9d81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'photo')
    # ### end Alembic commands ###
