"""empty message

Revision ID: 8aae38051f29
Revises: 
Create Date: 2020-05-10 23:28:44.911826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aae38051f29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tag', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'tags', ['tag'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'tag')
    # ### end Alembic commands ###
