"""empty message

Revision ID: dc9d1b1ba7a8
Revises: 59043f318c4f
Create Date: 2020-05-13 10:51:16.461299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9d1b1ba7a8'
down_revision = '59043f318c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'subscribe')
    op.add_column('users', sa.Column('subscribe', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribe')
    op.add_column('posts', sa.Column('subscribe', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
