"""empty message

Revision ID: df86ddd28730
Revises: 8aae38051f29
Create Date: 2020-05-11 00:02:45.019242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df86ddd28730'
down_revision = '8aae38051f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.drop_constraint('posts_tag_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'tags', ['tag_id'], ['id'])
    op.drop_column('posts', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_tag_fkey', 'posts', 'tags', ['tag'], ['id'])
    op.drop_column('posts', 'tag_id')
    # ### end Alembic commands ###
